name: deploy

on:
    push:
        branches: [master]
permissions:
    contents: read

jobs:
    deploy:
        name: deploy
        runs-on: ubuntu-latest
        steps:
            - name: executing remote ssh commands using password
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.SSH_HOST }}
                  username: ${{ secrets.SSH_USERNAME }}
                  key: ${{ secrets.SSH_PRIVATE_KEY }}
                  port: ${{ secrets.SSH_PORT }}
                  script: |
                      cd /home/${{secrets.SSH_USERNAME}}/public_html/review-as-a-service
                      bash
                      git reset --hard
                      GNUTLS_CPUID_OVERRIDE=0x1 git pull
                      GNUTLS_CPUID_OVERRIDE=0x1 composer install --optimize-autoloader --no-dev
                      GNUTLS_CPUID_OVERRIDE=0x1 npm install --loglevel warn
                      php artisan migrate --force
                      npm run build
                      php artisan config:cache
                      php artisan route:cache
                      php artisan view:cache
                      php artisan optimize
