name: deploy

on:
    push:
        branches: [master]
permissions:
    contents: read

jobs:
    deploy:
        name: deploy
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: '16'
            - name: update-liara
              env:
                  LIARA_TOKEN: ${{ secrets.LIARA_API_TOKEN }}
              run: |
                  npm i -g @liara/cli@3
                  liara deploy --app="codereviewpals" --api-token="$LIARA_TOKEN"
                  liara shell --app="codereviewpals" --api-token="$LIARA_TOKEN" --command="bash deploy.sh"
